### ISSUE TITLE
Analysis roadmap

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/zizmor#1]
- [x] Auditing of action definitions (i.e. `action.yml`) #173 
- [x] Accidental credential persistence
    - [x] "ArtiPACKED"
- [x] Insecure/fundamentally dangerous workflow triggers
    - [x] `pull_request_target`
    - [x] `workflow_run`: #33 
- [x] Insecure/excessive permissions
- [x] Self-hosted runners/runner escapes
- [x] Cache poisoning https://github.com/woodruffw/zizmor/issues/261
- [x] Impostor commits
- [x] Ref confusion (e.g. branch/tag confusion)
- [x] Bad practices for third-party actions
    - [x] Using `pypa/gh-action-pypi-publish` without trusted publishing
    - [x] Using `rubygems/release-gem` without trusted publishing
- [x] Hardcoded `container`/`service` credentials
- [x] Suggest upgrades for common 3p workflows, e.g. `gh-action-pypi-publish@master` should be `@release/v1`.
    - [x] See #59 
- [ ] Out-of-date Dependabot version comments
- [x] Unpinned actions ~~(this should probably be pedantic only)~~
    - [x] https://github.com/woodruffw/zizmor/issues/141
- [ ] Bad YAML string/int conversions (these will be annoying to detect, since we'd need to go back up to the original span to see if the deserialized form diverges)
    - [x] https://github.com/dtolnay/rust-toolchain/issues/112
- [x] #36
    - [ ] https://osv.dev/list?q=&ecosystem=GitHub+Actions
- [x] `GITHUB_ENV` usage: #156 
- [x] Insecure workflow commands: https://github.com/woodruffw/zizmor/issues/171
- [ ] Secrets outside of environments: https://github.com/woodruffw/zizmor/issues/184
- [ ] Old/stale action usage: https://github.com/woodruffw/zizmor/issues/260

**Comment by woodruffw** [comment]
Closing in favor of per-issue tracking.
